export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_LOGIN = 'USER_LOGIN';
export const POPULATE_USER_INFO = 'POPULATE_USER_INFO';
export const USER_LOGGING_IN = 'USE_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const TRY_AUTO_LOGIN = 'TRY_AUTO_LOGIN';
export const TRY_AUTO_LOGIN_SUCCESS= 'TRY_AUTO_LOGIN_SUCCESS';
export const TRY_AUTO_LOGIN_FAIL= 'TRY_AUTO_LOGIN_FAIL';


export const ITEM_DROP_IMAGE = 'ITEM_DROP_IMAGE';
export const ITEM_NEW_IMAGE = 'ITEM_NEW_IMAGE';
export const ITEM_DELETE_IMAGE = 'ITEM_DELETE_IMAGE';
export const ITEM_CREATE = 'ITEM_CREATE';
export const ITEM_CREATING = 'ITEM_CREATING';
export const ITEM_CREATED = 'ITEM_CREATED';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEM_CATEGORIES_FAIL = 'GET_ITEM_CATEGORIES_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
export const GET_SINGLE_ITEM_FAIL = 'GET_SINGLE_ITEM_FAIL';
export const GET_SINGLE_ITEM_SUCCESS = 'GET_SINGLE_ITEM_SUCCESS';

//new item
export const GET_ITEM_CATEGORIES = 'GET_ITEM_CATEGORIES';
export const POPUPLATE_ITEM_CATEGORIES = 'POPULATE_ITEM_CATEGORIES';
export const NEW_ITEM_INFO_INPUT = 'NEW_ITEM_INFO_INPUT';
export const STORE_IMAGE_SRC = 'STORE_IMAGE_SRC';