export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGING_IN = 'USE_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ITEM_NEW_IMAGE = 'ITEM_NEW_IMAGE';
export const ITEM_DELETE_IMAGE = 'ITEM_DELETE_IMAGE';
export const ITEM_CREATE = 'ITEM_CREATE';
export const ITEM_CREATING = 'ITEM_CREATING';
export const ITEM_CREATED = 'ITEM_CREATED';