
// modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';


// user
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_LOGIN = 'USER_LOGIN';
export const POPULATE_USER_INFO = 'POPULATE_USER_INFO';
export const USER_LOGGING_IN = 'USE_LOGGING_IN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const TRY_AUTO_LOGIN = 'TRY_AUTO_LOGIN';
export const TRY_AUTO_LOGIN_SUCCESS= 'TRY_AUTO_LOGIN_SUCCESS';
export const TRY_AUTO_LOGIN_FAIL= 'TRY_AUTO_LOGIN_FAIL';
export const TRY_LOGOUT = 'TRY_LOGOUT';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const RESET_FORM = 'RESET_FORM';

//profile
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const POPULATE_PROFILE_ITEMS = 'POPULATE_PROFILE_ITEMS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';

//item
export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEM_CATEGORIES_FAIL = 'GET_ITEM_CATEGORIES_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
export const GET_SINGLE_ITEM_FAIL = 'GET_SINGLE_ITEM_FAIL';
export const GET_SINGLE_ITEM_SUCCESS = 'GET_SINGLE_ITEM_SUCCESS';


// loginFormPopUp
export const FORM_INPUT = 'FORM_INPUT';
export const CHECK_FORM_VALIDITY = 'CHECK_FORM_VALIDITY';
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP';


//new item
export const GET_ITEM_CATEGORIES = 'GET_ITEM_CATEGORIES';
export const POPUPLATE_ITEM_CATEGORIES = 'POPULATE_ITEM_CATEGORIES';
export const NEW_ITEM_INFO_INPUT = 'NEW_ITEM_INFO_INPUT';
export const STORE_IMAGE_SRC = 'STORE_IMAGE_SRC';
export const POPULATE_PREVIEW_IMAGE_SRC = 'POPULATE_PREVIEW_IMAGE_SRC';
export const STORE_IMAGE_EL_REF = 'STORE_IMAGE_EL_REF';
export const SELECT_ITEM_CATEGORY = 'SELECT_ITEM_CATEGORY';
export const SELECT_ITEM_CONDITION = 'SELECT_ITEM_CONDITION';
export const LIST_NEW_ITEM = 'LIST_NEW_ITEM';
export const LIST_NEW_ITEM_SUCCESS = 'LIST_NEW_ITEM_SUCCESS';
export const LIST_NEW_ITEM_FAIL = 'LIST_NEW_ITEM_FAIL';